# Generated by Django 4.2.7 on 2023-12-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default=None, upload_to='pics'),
            preserve_default=False,
        ),
    ]
